### ISSUE TITLE
deliverable selection list dissappears when one is selected

### ISSUE THREAD

**Issue by ghost** [skuretski/cassiopeiaFront#11] opened 2017-05-18 03:45 UTC
The list of deliverables disappears when a deliverable is selected.  It would be better if the selected deliverable was highlighted but the list didn't disappear when would allow the user to select other deliverables for the same project.

**Comment by skuretski** [comment] 2017-05-20 01:19
I believe this is resolved. Deliverables on left side navigation appears to be running as intended on 5/19/2017. Marking as closed.

**Closed as completed by skuretski** 2017-05-20 01:19 UTC
